"""
Constants for dataset assembly.
"""

BASE_PATH = r".\Dataset\Prepared_st2\\"

BATCH_SIZE = 24
REGULAR_BATCHES = 1000
REGULARIZATION_BATCHES = 500
REGULAR_COUNT = REGULAR_BATCHES * BATCH_SIZE
REGULARIZATION_COUNT = REGULARIZATION_BATCHES * BATCH_SIZE
TOTAL_STEPS = REGULAR_BATCHES + REGULARIZATION_BATCHES

EVAL_BATCH_SIZE = 18
EVAL_BATCHES = 30
REPLACE_EVAL_THRESHOLD = 0.05

HIGH_LOSS_THRESHOLD = 1
MEDIUM_LOSS_MIN = 0.25
LOW_LOSS_MIN = 0.0

# Deterministic RNG seed for stable shuffles across runs
RNG_SEED = 1337
